import { timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Shared column conventions for the HRIS schema.
 *
 * - UUID primary keys, generated by the database (`gen_random_uuid()`).
 * - Timestamps stored as `timestamptz` (always UTC) and returned as `Date`.
 * - `updated_at` is maintained by Drizzle's `$onUpdate` hook.
 * - Soft-delete (`deleted_at`) is available as a convention for tables that
 *   need archival in later phases; no Phase 2 table requires it yet.
 */

export const uuidId = () => uuid("id").primaryKey().defaultRandom();

export const createdAt = () =>
  timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow();

export const updatedAt = () =>
  timestamp("updated_at", { withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/** Optional soft-delete sentinel for future archival-aware tables. */
export const deletedAt = () =>
  timestamp("deleted_at", { withTimezone: true, mode: "date" });
